# Generated by Django 2.0.7 on 2019-01-20 22:12

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph', models.CharField(max_length=20)),
                ('dissolved_oxygen', models.CharField(max_length=20)),
                ('electric_conductivity', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StationPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=20)),
                ('geo', django.contrib.gis.db.models.fields.PointField(blank=True, srid=3116)),
            ],
        ),
        migrations.AddField(
            model_name='stationdata',
            name='station_point',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data.StationPoint'),
        ),
    ]
