# Generated by Django 2.0.7 on 2018-08-28 14:39

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PointData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(blank=True)),
                ('long', models.FloatField(blank=True)),
                ('geo', django.contrib.gis.db.models.fields.PointField(blank=True, srid=3116)),
            ],
        ),
    ]
